// Code generated by ObjectBox; DO NOT EDIT.
// Learn more about defining entities and generating this file - visit https://golang.objectbox.io/entity-annotations

package model

import (
	"errors"
	"github.com/google/flatbuffers/go"
	"github.com/objectbox/objectbox-go/objectbox"
	"github.com/objectbox/objectbox-go/objectbox/fbutils"
)

type post_EntityInfo struct {
	objectbox.Entity
	Uid uint64
}

var PostBinding = post_EntityInfo{
	Entity: objectbox.Entity{
		Id: 1,
	},
	Uid: 3149404172376072906,
}

// Post_ contains type-based Property helpers to facilitate some common operations such as Queries.
var Post_ = struct {
	Id          *objectbox.PropertyUint64
	Title       *objectbox.PropertyString
	Author      *objectbox.PropertyString
	Description *objectbox.PropertyString
	DateCreated *objectbox.PropertyInt64
}{
	Id: &objectbox.PropertyUint64{
		BaseProperty: &objectbox.BaseProperty{
			Id:     1,
			Entity: &PostBinding.Entity,
		},
	},
	Title: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     2,
			Entity: &PostBinding.Entity,
		},
	},
	Author: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     3,
			Entity: &PostBinding.Entity,
		},
	},
	Description: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     4,
			Entity: &PostBinding.Entity,
		},
	},
	DateCreated: &objectbox.PropertyInt64{
		BaseProperty: &objectbox.BaseProperty{
			Id:     5,
			Entity: &PostBinding.Entity,
		},
	},
}

// GeneratorVersion is called by ObjectBox to verify the compatibility of the generator used to generate this code
func (post_EntityInfo) GeneratorVersion() int {
	return 6
}

// AddToModel is called by ObjectBox during model build
func (post_EntityInfo) AddToModel(model *objectbox.Model) {
	model.Entity("Post", 1, 3149404172376072906)
	model.Property("Id", 6, 1, 1565924739266444062)
	model.PropertyFlags(1)
	model.Property("Title", 9, 2, 5083440040409085299)
	model.Property("Author", 9, 3, 6136335573209237216)
	model.Property("Description", 9, 4, 4965075241166942970)
	model.Property("DateCreated", 10, 5, 4363536297493949015)
	model.EntityLastPropertyId(5, 4363536297493949015)
}

// GetId is called by ObjectBox during Put operations to check for existing ID on an object
func (post_EntityInfo) GetId(object interface{}) (uint64, error) {
	return object.(*Post).Id, nil
}

// SetId is called by ObjectBox during Put to update an ID on an object that has just been inserted
func (post_EntityInfo) SetId(object interface{}, id uint64) error {
	object.(*Post).Id = id
	return nil
}

// PutRelated is called by ObjectBox to put related entities before the object itself is flattened and put
func (post_EntityInfo) PutRelated(ob *objectbox.ObjectBox, object interface{}, id uint64) error {
	return nil
}

// Flatten is called by ObjectBox to transform an object to a FlatBuffer
func (post_EntityInfo) Flatten(object interface{}, fbb *flatbuffers.Builder, id uint64) error {
	obj := object.(*Post)
	var propDateCreated int64
	{
		var err error
		propDateCreated, err = objectbox.TimeInt64ConvertToDatabaseValue(obj.DateCreated)
		if err != nil {
			return errors.New("converter objectbox.TimeInt64ConvertToDatabaseValue() failed on Post.DateCreated: " + err.Error())
		}
	}

	var offsetTitle = fbutils.CreateStringOffset(fbb, obj.Title)
	var offsetAuthor = fbutils.CreateStringOffset(fbb, obj.Author)
	var offsetDescription = fbutils.CreateStringOffset(fbb, obj.Description)

	// build the FlatBuffers object
	fbb.StartObject(5)
	fbutils.SetUint64Slot(fbb, 0, id)
	fbutils.SetUOffsetTSlot(fbb, 1, offsetTitle)
	fbutils.SetUOffsetTSlot(fbb, 2, offsetAuthor)
	fbutils.SetUOffsetTSlot(fbb, 3, offsetDescription)
	fbutils.SetInt64Slot(fbb, 4, propDateCreated)
	return nil
}

// Load is called by ObjectBox to load an object from a FlatBuffer
func (post_EntityInfo) Load(ob *objectbox.ObjectBox, bytes []byte) (interface{}, error) {
	if len(bytes) == 0 { // sanity check, should "never" happen
		return nil, errors.New("can't deserialize an object of type 'Post' - no data received")
	}

	var table = &flatbuffers.Table{
		Bytes: bytes,
		Pos:   flatbuffers.GetUOffsetT(bytes),
	}

	var propId = table.GetUint64Slot(4, 0)

	propDateCreated, err := objectbox.TimeInt64ConvertToEntityProperty(fbutils.GetInt64Slot(table, 12))
	if err != nil {
		return nil, errors.New("converter objectbox.TimeInt64ConvertToEntityProperty() failed on Post.DateCreated: " + err.Error())
	}

	return &Post{
		Id:          propId,
		Title:       fbutils.GetStringSlot(table, 6),
		Author:      fbutils.GetStringSlot(table, 8),
		Description: fbutils.GetStringSlot(table, 10),
		DateCreated: propDateCreated,
	}, nil
}

// MakeSlice is called by ObjectBox to construct a new slice to hold the read objects
func (post_EntityInfo) MakeSlice(capacity int) interface{} {
	return make([]*Post, 0, capacity)
}

// AppendToSlice is called by ObjectBox to fill the slice of the read objects
func (post_EntityInfo) AppendToSlice(slice interface{}, object interface{}) interface{} {
	if object == nil {
		return append(slice.([]*Post), nil)
	}
	return append(slice.([]*Post), object.(*Post))
}

// Box provides CRUD access to Post objects
type PostBox struct {
	*objectbox.Box
}

// BoxForPost opens a box of Post objects
func BoxForPost(ob *objectbox.ObjectBox) *PostBox {
	return &PostBox{
		Box: ob.InternalBox(1),
	}
}

// Put synchronously inserts/updates a single object.
// In case the Id is not specified, it would be assigned automatically (auto-increment).
// When inserting, the Post.Id property on the passed object will be assigned the new ID as well.
func (box *PostBox) Put(object *Post) (uint64, error) {
	return box.Box.Put(object)
}

// Insert synchronously inserts a single object. As opposed to Put, Insert will fail if given an ID that already exists.
// In case the Id is not specified, it would be assigned automatically (auto-increment).
// When inserting, the Post.Id property on the passed object will be assigned the new ID as well.
func (box *PostBox) Insert(object *Post) (uint64, error) {
	return box.Box.Insert(object)
}

// Update synchronously updates a single object.
// As opposed to Put, Update will fail if an object with the same ID is not found in the database.
func (box *PostBox) Update(object *Post) error {
	return box.Box.Update(object)
}

// PutAsync asynchronously inserts/updates a single object.
// Deprecated: use box.Async().Put() instead
func (box *PostBox) PutAsync(object *Post) (uint64, error) {
	return box.Box.PutAsync(object)
}

// PutMany inserts multiple objects in single transaction.
// In case Ids are not set on the objects, they would be assigned automatically (auto-increment).
//
// Returns: IDs of the put objects (in the same order).
// When inserting, the Post.Id property on the objects in the slice will be assigned the new IDs as well.
//
// Note: In case an error occurs during the transaction, some of the objects may already have the Post.Id assigned
// even though the transaction has been rolled back and the objects are not stored under those IDs.
//
// Note: The slice may be empty or even nil; in both cases, an empty IDs slice and no error is returned.
func (box *PostBox) PutMany(objects []*Post) ([]uint64, error) {
	return box.Box.PutMany(objects)
}

// Get reads a single object.
//
// Returns nil (and no error) in case the object with the given ID doesn't exist.
func (box *PostBox) Get(id uint64) (*Post, error) {
	object, err := box.Box.Get(id)
	if err != nil {
		return nil, err
	} else if object == nil {
		return nil, nil
	}
	return object.(*Post), nil
}

// GetMany reads multiple objects at once.
// If any of the objects doesn't exist, its position in the return slice is nil
func (box *PostBox) GetMany(ids ...uint64) ([]*Post, error) {
	objects, err := box.Box.GetMany(ids...)
	if err != nil {
		return nil, err
	}
	return objects.([]*Post), nil
}

// GetManyExisting reads multiple objects at once, skipping those that do not exist.
func (box *PostBox) GetManyExisting(ids ...uint64) ([]*Post, error) {
	objects, err := box.Box.GetManyExisting(ids...)
	if err != nil {
		return nil, err
	}
	return objects.([]*Post), nil
}

// GetAll reads all stored objects
func (box *PostBox) GetAll() ([]*Post, error) {
	objects, err := box.Box.GetAll()
	if err != nil {
		return nil, err
	}
	return objects.([]*Post), nil
}

// Remove deletes a single object
func (box *PostBox) Remove(object *Post) error {
	return box.Box.Remove(object)
}

// RemoveMany deletes multiple objects at once.
// Returns the number of deleted object or error on failure.
// Note that this method will not fail if an object is not found (e.g. already removed).
// In case you need to strictly check whether all of the objects exist before removing them,
// you can execute multiple box.Contains() and box.Remove() inside a single write transaction.
func (box *PostBox) RemoveMany(objects ...*Post) (uint64, error) {
	var ids = make([]uint64, len(objects))
	for k, object := range objects {
		ids[k] = object.Id
	}
	return box.Box.RemoveIds(ids...)
}

// Creates a query with the given conditions. Use the fields of the Post_ struct to create conditions.
// Keep the *PostQuery if you intend to execute the query multiple times.
// Note: this function panics if you try to create illegal queries; e.g. use properties of an alien type.
// This is typically a programming error. Use QueryOrError instead if you want the explicit error check.
func (box *PostBox) Query(conditions ...objectbox.Condition) *PostQuery {
	return &PostQuery{
		box.Box.Query(conditions...),
	}
}

// Creates a query with the given conditions. Use the fields of the Post_ struct to create conditions.
// Keep the *PostQuery if you intend to execute the query multiple times.
func (box *PostBox) QueryOrError(conditions ...objectbox.Condition) (*PostQuery, error) {
	if query, err := box.Box.QueryOrError(conditions...); err != nil {
		return nil, err
	} else {
		return &PostQuery{query}, nil
	}
}

// Async provides access to the default Async Box for asynchronous operations. See PostAsyncBox for more information.
func (box *PostBox) Async() *PostAsyncBox {
	return &PostAsyncBox{AsyncBox: box.Box.Async()}
}

// PostAsyncBox provides asynchronous operations on Post objects.
//
// Asynchronous operations are executed on a separate internal thread for better performance.
//
// There are two main use cases:
//
// 1) "execute & forget:" you gain faster put/remove operations as you don't have to wait for the transaction to finish.
//
// 2) Many small transactions: if your write load is typically a lot of individual puts that happen in parallel,
// this will merge small transactions into bigger ones. This results in a significant gain in overall throughput.
//
// In situations with (extremely) high async load, an async method may be throttled (~1ms) or delayed up to 1 second.
// In the unlikely event that the object could still not be enqueued (full queue), an error will be returned.
//
// Note that async methods do not give you hard durability guarantees like the synchronous Box provides.
// There is a small time window in which the data may not have been committed durably yet.
type PostAsyncBox struct {
	*objectbox.AsyncBox
}

// AsyncBoxForPost creates a new async box with the given operation timeout in case an async queue is full.
// The returned struct must be freed explicitly using the Close() method.
// It's usually preferable to use PostBox::Async() which takes care of resource management and doesn't require closing.
func AsyncBoxForPost(ob *objectbox.ObjectBox, timeoutMs uint64) *PostAsyncBox {
	var async, err = objectbox.NewAsyncBox(ob, 1, timeoutMs)
	if err != nil {
		panic("Could not create async box for entity ID 1: %s" + err.Error())
	}
	return &PostAsyncBox{AsyncBox: async}
}

// Put inserts/updates a single object asynchronously.
// When inserting a new object, the Id property on the passed object will be assigned the new ID the entity would hold
// if the insert is ultimately successful. The newly assigned ID may not become valid if the insert fails.
func (asyncBox *PostAsyncBox) Put(object *Post) (uint64, error) {
	return asyncBox.AsyncBox.Put(object)
}

// Insert a single object asynchronously.
// The Id property on the passed object will be assigned the new ID the entity would hold if the insert is ultimately
// successful. The newly assigned ID may not become valid if the insert fails.
// Fails silently if an object with the same ID already exists (this error is not returned).
func (asyncBox *PostAsyncBox) Insert(object *Post) (id uint64, err error) {
	return asyncBox.AsyncBox.Insert(object)
}

// Update a single object asynchronously.
// The object must already exists or the update fails silently (without an error returned).
func (asyncBox *PostAsyncBox) Update(object *Post) error {
	return asyncBox.AsyncBox.Update(object)
}

// Remove deletes a single object asynchronously.
func (asyncBox *PostAsyncBox) Remove(object *Post) error {
	return asyncBox.AsyncBox.Remove(object)
}

// Query provides a way to search stored objects
//
// For example, you can find all Post which Id is either 42 or 47:
//
//	box.Query(Post_.Id.In(42, 47)).Find()
type PostQuery struct {
	*objectbox.Query
}

// Find returns all objects matching the query
func (query *PostQuery) Find() ([]*Post, error) {
	objects, err := query.Query.Find()
	if err != nil {
		return nil, err
	}
	return objects.([]*Post), nil
}

// Offset defines the index of the first object to process (how many objects to skip)
func (query *PostQuery) Offset(offset uint64) *PostQuery {
	query.Query.Offset(offset)
	return query
}

// Limit sets the number of elements to process by the query
func (query *PostQuery) Limit(limit uint64) *PostQuery {
	query.Query.Limit(limit)
	return query
}
